#!/bin/zsh

echo "Enter master password: "
read -s pswd
echo "Enter instructions: "
read var1

if [[ "$var1" = "encrypt" ]]; then
  echo "Enter account name, username, password"
  read -s var2 var3 var4
  /Users/andy/Documents/Rust_Projects/lattice/target/debug/lattice $pswd $var1 $var2 $var3 $var4
elif [[ "$var1" = "decrypt" ]]; then
  echo "Enter account name, and whether username or password"
  read var2 var3
  /Users/andy/Documents/Rust_Projects/lattice/target/debug/lattice $pswd $var1 $var2 $var3 $var4 | pbcopy
elif [[ "$var1" = "keygen" ]]; then
  /Users/andy/Documents/Rust_Projects/lattice/target/debug/lattice $pswd $var1
fi

